### ISSUE TITLE
no work scam bro scam no work11!!!!!

### ISSUE THREAD

**Issue by upyxs** [mqhirr/Quark#1]
Bro this src scam im getting error while building "fmt is not namespace or class", "data2 undeclared identifier" im lazy to fix pls fix ok ty ok.

**Comment by mqhirr** [comment]
I'll make sure to fix it

**Comment by mqhirr** [comment]
should be fixed with this commit: https://github.com/mqhirr/Quark/tree/20caa9d4686d2ff9f34aa9d1a056e9ef8220fbe7
